name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Show Swift version
        run: swift --version

      - name: Build (release, warnings as errors)
        run: swift build -c release -Xswiftc -warnings-as-errors
